version: "3.2"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "V@qef4352249"
      ACCEPT_EULA: "Y"
    volumes:
      - db_data:/path/in/container
volumes:
  db_data: